version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      parameters:
        app_src_directory: harFileConverter/harFileConverter
      - maven/test # checkout, build, test, and upload test results
          
